# Generated by Django 5.2.15 on 2026-08-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="About Us", max_length=200, verbose_name="Title (EN)"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        default="درباره ما", max_length=200, verbose_name="Title (FA)"
                    ),
                ),
                ("content_en", models.TextField(verbose_name="Content (EN)")),
                ("content_fa", models.TextField(verbose_name="Content (FA)")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about/", verbose_name="Image"
                    ),
                ),
                (
                    "who_we_are_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Who We Are (EN)"
                    ),
                ),
                (
                    "who_we_are_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="Who We Are (FA)"
                    ),
                ),
                (
                    "we_are_expert_en",
                    models.TextField(
                        blank=True, default="", verbose_name="We Are Expert (EN)"
                    ),
                ),
                (
                    "we_are_expert_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="We Are Expert (FA)"
                    ),
                ),
                (
                    "why_choose_us_title_en",
                    models.CharField(
                        blank=True,
                        default="Why Choose Us",
                        max_length=200,
                        verbose_name="Why Choose Us Title (EN)",
                    ),
                ),
                (
                    "why_choose_us_title_fa",
                    models.CharField(
                        blank=True,
                        default="چرا ما را انتخاب کنید",
                        max_length=200,
                        verbose_name="Why Choose Us Title (FA)",
                    ),
                ),
                (
                    "why_choose_us_content_en",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Why Choose Us Content (EN)",
                    ),
                ),
                (
                    "why_choose_us_content_fa",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Why Choose Us Content (FA)",
                    ),
                ),
                (
                    "why_choose_us_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="Why Choose Us Image",
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        blank=True,
                        default="Get Started",
                        max_length=100,
                        verbose_name="CTA Text (EN)",
                    ),
                ),
                (
                    "cta_text_fa",
                    models.CharField(
                        blank=True,
                        default="شروع کنید",
                        max_length=100,
                        verbose_name="CTA Text (FA)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, default="#", max_length=500, verbose_name="CTA URL"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="Subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "is_replied",
                    models.BooleanField(default=False, verbose_name="Is Replied"),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventCountdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="Event Countdown",
                        max_length=200,
                        verbose_name="Title (EN)",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        default="شمارش معکوس رویداد",
                        max_length=200,
                        verbose_name="Title (FA)",
                    ),
                ),
                (
                    "subheading_en",
                    models.CharField(
                        default="Don't wait",
                        max_length=200,
                        verbose_name="Subheading (EN)",
                    ),
                ),
                (
                    "subheading_fa",
                    models.CharField(
                        default="منتظر نمانید",
                        max_length=200,
                        verbose_name="Subheading (FA)",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "ended_message_en",
                    models.CharField(
                        default="We are sorry, Event ended!",
                        max_length=300,
                        verbose_name="Ended Message (EN)",
                    ),
                ),
                (
                    "ended_message_fa",
                    models.CharField(
                        default="متأسفیم، رویداد تمام شده است!",
                        max_length=300,
                        verbose_name="Ended Message (FA)",
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        default="Get Started",
                        max_length=100,
                        verbose_name="CTA Text (EN)",
                    ),
                ),
                (
                    "cta_text_fa",
                    models.CharField(
                        default="شروع کنید",
                        max_length=100,
                        verbose_name="CTA Text (FA)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, default="#", max_length=500, verbose_name="CTA URL"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Event Countdown",
                "verbose_name_plural": "Event Countdowns",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, verbose_name="Title (FA)"),
                ),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_fa", models.TextField(verbose_name="Description (FA)")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Icon"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("services", "Services"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Page",
                    ),
                ),
                (
                    "heading_en",
                    models.CharField(max_length=300, verbose_name="Heading (EN)"),
                ),
                (
                    "heading_fa",
                    models.CharField(max_length=300, verbose_name="Heading (FA)"),
                ),
                (
                    "subheading_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Subheading (EN)",
                    ),
                ),
                (
                    "subheading_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Subheading (FA)",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hero/",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="CTA Text (EN)",
                    ),
                ),
                (
                    "cta_text_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="CTA Text (FA)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, default="#", max_length=500, verbose_name="CTA URL"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("home_about", "Home About Section"),
                            ("home_why", "Home Why Choose Us"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, verbose_name="Title (FA)"),
                ),
                (
                    "subheading_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Subheading (EN)",
                    ),
                ),
                (
                    "subheading_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Subheading (FA)",
                    ),
                ),
                ("content_en", models.TextField(verbose_name="Content (EN)")),
                ("content_fa", models.TextField(verbose_name="Content (FA)")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/", verbose_name="Image"
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        blank=True,
                        default="Get Started",
                        max_length=100,
                        verbose_name="CTA Text (EN)",
                    ),
                ),
                (
                    "cta_text_fa",
                    models.CharField(
                        blank=True,
                        default="شروع کنید",
                        max_length=100,
                        verbose_name="CTA Text (FA)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, default="#", max_length=500, verbose_name="CTA URL"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Home Section",
                "verbose_name_plural": "Home Sections",
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, verbose_name="Title (FA)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("content_en", models.TextField(verbose_name="Content (EN)")),
                ("content_fa", models.TextField(verbose_name="Content (FA)")),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Meta Title (EN)",
                    ),
                ),
                (
                    "meta_title_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Meta Title (FA)",
                    ),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Meta Description (EN)"
                    ),
                ),
                (
                    "meta_description_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="Meta Description (FA)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        default=False, verbose_name="Show in Navigation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (EN)")),
                ("name_fa", models.CharField(max_length=200, verbose_name="Name (FA)")),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_fa", models.TextField(verbose_name="Description (FA)")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="$", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "cents",
                    models.CharField(default=".99", max_length=5, verbose_name="Cents"),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="Is Popular (Highlighted)"
                    ),
                ),
                (
                    "button_text_en",
                    models.CharField(
                        default="Buy", max_length=100, verbose_name="Button Text (EN)"
                    ),
                ),
                (
                    "button_text_fa",
                    models.CharField(
                        default="خرید", max_length=100, verbose_name="Button Text (FA)"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        max_length=500,
                        verbose_name="Button URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (EN)"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, verbose_name="Title (FA)"),
                ),
                ("description_en", models.TextField(verbose_name="Description (EN)")),
                ("description_fa", models.TextField(verbose_name="Description (FA)")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("camera", "Camera"),
                            ("gear", "Settings/Gear"),
                            ("image", "Image"),
                            ("layers", "Layers"),
                            ("window", "Window/Web"),
                            ("bag-check", "eCommerce"),
                            ("bullseye", "Branding"),
                            ("phone", "Mobile"),
                        ],
                        default="gear",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "custom_svg",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Paste custom SVG code here (overrides icon selection)",
                        verbose_name="Custom SVG Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        default="AM Business",
                        max_length=200,
                        verbose_name="Site Name (EN)",
                    ),
                ),
                (
                    "site_name_fa",
                    models.CharField(
                        default="ای ام بیزینس",
                        max_length=200,
                        verbose_name="Site Name (FA)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Meta Description (EN)"
                    ),
                ),
                (
                    "meta_description_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="Meta Description (FA)"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Address (EN)"
                    ),
                ),
                (
                    "address_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="Address (FA)"
                    ),
                ),
                (
                    "copyright_text_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Copyright (EN)",
                    ),
                ),
                (
                    "copyright_text_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Copyright (FA)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("dribbble", "Dribbble"),
                            ("youtube", "YouTube"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("github", "GitHub"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Platform",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom icon class (e.g., icon-facebook)",
                        max_length=100,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StatCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=200, verbose_name="Label (EN)"),
                ),
                (
                    "label_fa",
                    models.CharField(max_length=200, verbose_name="Label (FA)"),
                ),
                ("value", models.PositiveIntegerField(default=0, verbose_name="Value")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Stat Counter",
                "verbose_name_plural": "Stat Counters",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "position_en",
                    models.CharField(max_length=200, verbose_name="Position (EN)"),
                ),
                (
                    "position_fa",
                    models.CharField(max_length=200, verbose_name="Position (FA)"),
                ),
                ("bio_en", models.TextField(verbose_name="Bio (EN)")),
                ("bio_fa", models.TextField(verbose_name="Bio (FA)")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="Photo"
                    ),
                ),
                (
                    "photo_square",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team/",
                        verbose_name="Square Photo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("quote_en", models.TextField(verbose_name="Quote (EN)")),
                ("quote_fa", models.TextField(verbose_name="Quote (FA)")),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="Author Name"),
                ),
                (
                    "author_role_en",
                    models.CharField(max_length=200, verbose_name="Author Role (EN)"),
                ),
                (
                    "author_role_fa",
                    models.CharField(max_length=200, verbose_name="Author Role (FA)"),
                ),
                (
                    "author_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Author Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, verbose_name="Title (EN)"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=100, verbose_name="Title (FA)"),
                ),
                (
                    "url",
                    models.CharField(default="#", max_length=500, verbose_name="URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.navigation",
                        verbose_name="Parent Menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "ordering": ["order"],
            },
        ),
    ]
