# Generated by Django 4.2.30 on 2026-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="custom_icon",
            field=models.ImageField(
                blank=True,
                help_text="Upload a custom icon image (overrides icon selection)",
                null=True,
                upload_to="services/icons/",
                verbose_name="Custom Icon Image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_email",
            field=models.EmailField(
                blank=True,
                default="info@ambusinessintl.com",
                max_length=254,
                verbose_name="Footer Email",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_instagram",
            field=models.CharField(
                blank=True,
                default="ambusinessintl",
                max_length=200,
                verbose_name="Instagram Username",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_linkedin",
            field=models.CharField(
                blank=True,
                default="ambusinessintl",
                max_length=200,
                verbose_name="LinkedIn Username",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_location",
            field=models.CharField(
                blank=True,
                default="Murtafaat Al Matar, Al Seeb, Muscat Governorate",
                max_length=500,
                verbose_name="Footer Location",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_phone",
            field=models.CharField(
                blank=True,
                default="+968 94 749 749",
                max_length=50,
                verbose_name="Footer Phone",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp",
            field=models.CharField(
                blank=True,
                default="+968 94 749 749",
                max_length=50,
                verbose_name="WhatsApp Number",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a custom icon image (overrides icon class)",
                null=True,
                upload_to="social-icons/",
                verbose_name="Custom Icon Image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="copyright_text_en",
            field=models.CharField(
                blank=True,
                default="By Am Business Creative Division",
                max_length=500,
                verbose_name="Copyright (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="copyright_text_fa",
            field=models.CharField(
                blank=True,
                default="توسط تیم خلاق ای ام بیزینس",
                max_length=500,
                verbose_name="Copyright (FA)",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter/X"),
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("dribbble", "Dribbble"),
                    ("youtube", "YouTube"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("github", "GitHub"),
                    ("phone", "Phone"),
                    ("location", "Location"),
                    ("email", "Email"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(blank=True, default="#", verbose_name="URL"),
        ),
    ]
