# Generated by Django 4.2.30 on 2026-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_custom_icon_sitesettings_footer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content_ar',
            field=models.TextField(blank=True, default='', verbose_name='Content (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text_ar',
            field=models.CharField(blank=True, default='ابدأ الآن', max_length=100, verbose_name='CTA Text (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ar',
            field=models.CharField(blank=True, default='من نحن', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='we_are_expert_ar',
            field=models.TextField(blank=True, default='', verbose_name='We Are Expert (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='who_we_are_ar',
            field=models.TextField(blank=True, default='', verbose_name='Who We Are (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_choose_us_content_ar',
            field=models.TextField(blank=True, default='', verbose_name='Why Choose Us Content (AR)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_choose_us_title_ar',
            field=models.CharField(blank=True, default='لماذا تختارنا', max_length=200, verbose_name='Why Choose Us Title (AR)'),
        ),
        migrations.AddField(
            model_name='eventcountdown',
            name='cta_text_ar',
            field=models.CharField(blank=True, default='ابدأ الآن', max_length=100, verbose_name='CTA Text (AR)'),
        ),
        migrations.AddField(
            model_name='eventcountdown',
            name='ended_message_ar',
            field=models.CharField(blank=True, default='نأسف، انتهى الحدث!', max_length=300, verbose_name='Ended Message (AR)'),
        ),
        migrations.AddField(
            model_name='eventcountdown',
            name='subheading_ar',
            field=models.CharField(blank=True, default='لا تنتظر', max_length=200, verbose_name='Subheading (AR)'),
        ),
        migrations.AddField(
            model_name='eventcountdown',
            name='title_ar',
            field=models.CharField(blank=True, default='العد التنازلي للحدث', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (AR)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CTA Text (AR)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Heading (AR)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Subheading (AR)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_ar',
            field=models.TextField(blank=True, default='', verbose_name='Content (AR)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='cta_text_ar',
            field=models.CharField(blank=True, default='ابدأ الآن', max_length=100, verbose_name='CTA Text (AR)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subheading (AR)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ar',
            field=models.TextField(blank=True, default='', verbose_name='Content (AR)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description (AR)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Meta Title (AR)'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text_ar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Button Text (AR)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (AR)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (AR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Description (AR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ar',
            field=models.TextField(blank=True, default='', verbose_name='Address (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ar',
            field=models.CharField(blank=True, default='من فريق إي إم بيزنس الإبداعي', max_length=500, verbose_name='Copyright (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ar',
            field=models.CharField(default='إي إم بيزنس', max_length=200, verbose_name='Site Name (AR)'),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Label (AR)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ar',
            field=models.TextField(blank=True, default='', verbose_name='Bio (AR)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Position (AR)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Author Role (AR)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_ar',
            field=models.TextField(blank=True, default='', verbose_name='Quote (AR)'),
        ),
    ]
