# Generated by Django 4.2.30 on 2026-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_arabic_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("countdown", "Event Countdown"),
                            ("pricing", "Pricing"),
                            ("features", "More Features"),
                            ("testimonials", "Testimonials"),
                            ("why", "Why AM Business"),
                            ("team", "Team"),
                            ("services", "Services"),
                            ("about_home", "Home About"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Section",
                    ),
                ),
                (
                    "subheading_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Subheading (EN)",
                    ),
                ),
                (
                    "subheading_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Subheading (FA)",
                    ),
                ),
                (
                    "subheading_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Subheading (AR)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Title (EN)",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Title (FA)",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Title (AR)",
                    ),
                ),
                (
                    "subtitle_en",
                    models.TextField(
                        blank=True, default="", verbose_name="Description (EN)"
                    ),
                ),
                (
                    "subtitle_fa",
                    models.TextField(
                        blank=True, default="", verbose_name="Description (FA)"
                    ),
                ),
                (
                    "subtitle_ar",
                    models.TextField(
                        blank=True, default="", verbose_name="Description (AR)"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pick from the palette or type a value such as #530e69",
                        max_length=20,
                        verbose_name="Background Colour",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Overrides the background colour",
                        null=True,
                        upload_to="sections/backgrounds/",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "overlay_color",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Overlay Colour",
                    ),
                ),
                (
                    "overlay_opacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = no overlay, 90 = almost opaque",
                        verbose_name="Overlay Opacity (%)",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Body Text Colour",
                    ),
                ),
                (
                    "heading_color",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Heading Colour",
                    ),
                ),
                (
                    "card_background",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Card Background",
                    ),
                ),
                (
                    "card_text_color",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Card Text Colour",
                    ),
                ),
                (
                    "show_pattern",
                    models.BooleanField(
                        default=True, verbose_name="Show Decorative Pattern"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Section Appearance",
                "verbose_name_plural": "Sections & Backgrounds",
                "ordering": ["section"],
            },
        ),
        migrations.AddField(
            model_name="eventcountdown",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Shown next to the countdown text (for example the company or event photo)",
                null=True,
                upload_to="countdown/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="eventcountdown",
            name="image_alt_ar",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Image Alt Text (AR)",
            ),
        ),
        migrations.AddField(
            model_name="eventcountdown",
            name="image_alt_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Image Alt Text (EN)",
            ),
        ),
        migrations.AddField(
            model_name="eventcountdown",
            name="image_alt_fa",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Image Alt Text (FA)",
            ),
        ),
        migrations.AddField(
            model_name="eventcountdown",
            name="image_position",
            field=models.CharField(
                choices=[("right", "Right of the text"), ("left", "Left of the text")],
                default="right",
                max_length=10,
                verbose_name="Image Position",
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About"),
                    ("services", "Services"),
                    ("contact", "Contact"),
                    ("portfolio", "Portfolio"),
                    ("projects", "Projects"),
                    ("blog", "Blog"),
                    ("pricing", "Pricing"),
                    ("team", "Team"),
                    ("gallery", "Gallery"),
                    ("custom", "Other / Custom Page"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Page",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_role_en",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Author Role (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_role_fa",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Author Role (FA)"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_en",
            field=models.TextField(blank=True, default="", verbose_name="Quote (EN)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote_fa",
            field=models.TextField(blank=True, default="", verbose_name="Quote (FA)"),
        ),
    ]
