# Generated by Django 4.2.30 on 2026-09-24 12:17

from django.db import migrations, models


def backfill_limits(apps, schema_editor):
    """Keep the previous homepage caps for services and team.

    Databases created before this migration already ran the earlier seed
    (which did not know about `item_limit`), so the caps are applied here as
    well.  Editors can change or clear them from the dashboard.
    """
    SectionStyle = apps.get_model("core", "SectionStyle")
    SectionStyle.objects.filter(section="services", item_limit=0).update(item_limit=8)
    SectionStyle.objects.filter(section="team", item_limit=0).update(item_limit=4)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_section_styles"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionstyle",
            name="item_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many cards/items of this section appear on the website. 0 = show every active item.",
                verbose_name="Items to Show",
            ),
        ),
        migrations.RunPython(backfill_limits, migrations.RunPython.noop),
    ]
