# Generated by Django 4.2.30 on 2026-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_section_item_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="custom_icon",
            field=models.ImageField(
                blank=True,
                help_text="Upload an icon image (PNG/SVG). Takes precedence over everything above.",
                null=True,
                upload_to="features/icons/",
                verbose_name="Custom Icon Image",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="custom_svg",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Paste SVG code here — it takes precedence over the icon above.",
                verbose_name="Custom SVG Icon",
            ),
        ),
        migrations.AlterField(
            model_name="eventcountdown",
            name="image_position",
            field=models.CharField(
                choices=[("right", "Right side"), ("left", "Left side")],
                default="right",
                max_length=10,
                verbose_name="Image Position",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("star", "Star / Quality"),
                    ("chart", "Growth chart"),
                    ("bullseye", "Branding / Target"),
                    ("rocket", "Launch / Startup"),
                    ("shield", "Trust / Security"),
                    ("idea", "Idea / Strategy"),
                    ("handshake", "Partnership"),
                    ("users", "Team / People"),
                    ("globe", "Global / Web"),
                    ("briefcase", "Business"),
                    ("camera", "Camera / Media"),
                    ("image", "Image / Design"),
                    ("layers", "Layers / Stack"),
                    ("window", "Website / Window"),
                    ("bag-check", "eCommerce"),
                    ("phone", "Mobile / App"),
                    ("check", "Check / Approval"),
                    ("clock", "Speed / Delivery"),
                    ("trophy", "Award / Result"),
                    ("megaphone", "Marketing"),
                    ("code", "Development"),
                    ("paint", "Creative / Brand"),
                    ("search", "Research / Analysis"),
                    ("gear", "Settings/Gear"),
                ],
                default="",
                help_text="Pick one of the built-in icons, or upload/paste your own below.",
                max_length=100,
                verbose_name="Icon",
            ),
        ),
    ]
