# Generated by Django 4.2.30 on 2026-09-25 13:12
#
# Trims HeroSection.page down to the pages that really exist.
#
# The choice list used to guess at pages this project does not have
# (portfolio, projects, blog, pricing, team, gallery).  None of them has a
# route, so a hero created for one was stored but never displayed.  The only
# real use for a per-page hero beyond the four fixed pages is a CMS page, which
# `frontend_page` looks up by its own slug, so the dashboard now offers the
# actual CMS pages dynamically (see core.views.hero_page_options) instead of a
# hardcoded guess list.
#
# Rows left behind for the removed guesses are deleted, unless a CMS page with
# that slug exists — in which case the hero is still reachable and is kept.

from django.db import migrations, models

REMOVED_PAGE_KEYS = ["portfolio", "projects", "blog", "pricing", "team", "gallery"]


def drop_orphan_heroes(apps, schema_editor):
    HeroSection = apps.get_model("core", "HeroSection")
    Page = apps.get_model("core", "Page")
    for key in REMOVED_PAGE_KEYS:
        if Page.objects.filter(slug=key).exists():
            continue  # a real CMS page uses this slug; its hero still renders
        HeroSection.objects.filter(page=key).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feature_icons'),
    ]

    operations = [
        migrations.RunPython(drop_orphan_heroes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='herosection',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('custom', 'Other / Custom Page')], max_length=50, unique=True, verbose_name='Page'),
        ),
    ]
