# Generated by Django 4.2.30 on 2026-09-25 13:28
#
# Makes "Sections & Backgrounds" the single place where a section's
# Subheading / Title / Description are edited.
#
# The Event Countdown and the two home blocks used to keep their own copies of
# that text on their own pages, which meant the same heading was editable from
# two screens and only one of them was ever displayed.  The values that are on
# screen today are copied into the matching SectionStyle row first, so nothing
# visible changes, and only then are the duplicate columns dropped.
#
# Copy priority mirrors what each template rendered before this migration:
#   countdown  : EventCountdown.title / .subheading
#   about_home : SectionStyle already won; HomeSection.content was the fallback
#   why        : SectionStyle, then HomeSection, then AboutSection.why_choose_us_*

from django.db import migrations, models

LANG_SUFFIXES = ("en", "fa", "ar")


def _copy_mapped(target, target_prefix, source, source_prefix):
    """Fill empty ``<target_prefix>_<lang>`` on `target` from the source field.

    Fields that already hold a value are never overwritten, so calling this
    repeatedly builds up the same fallback order the templates used.
    """
    if target is None or source is None:
        return []
    changed = []
    for lang in LANG_SUFFIXES:
        target_field = f"{target_prefix}_{lang}"
        if getattr(target, target_field, ""):
            continue
        value = getattr(source, f"{source_prefix}_{lang}", "")
        if value:
            setattr(target, target_field, value)
            changed.append(target_field)
    if changed:
        target.save(update_fields=changed)
    return changed


def move_text_into_section_styles(apps, schema_editor):
    SectionStyle = apps.get_model("core", "SectionStyle")
    EventCountdown = apps.get_model("core", "EventCountdown")
    HomeSection = apps.get_model("core", "HomeSection")
    AboutSection = apps.get_model("core", "AboutSection")

    # 1. Countdown: its own record was the only source for these two slots.
    countdown_style = SectionStyle.objects.filter(section="countdown").first()
    countdown = EventCountdown.objects.first()
    if countdown_style and countdown:
        _copy_mapped(countdown_style, "title", countdown, "title")
        _copy_mapped(countdown_style, "subheading", countdown, "subheading")

    # 2. Home "About": the section style already won, and HomeSection.content was
    #    the fallback body.  Its title/subheading were never displayed, so they
    #    are deliberately NOT copied — that would change the visible text.
    about_style = SectionStyle.objects.filter(section="about_home").first()
    home_about = HomeSection.objects.filter(section_type="home_about").first()
    if about_style and home_about:
        _copy_mapped(about_style, "subtitle", home_about, "content")

    # 3. Home "Why": SectionStyle, then the HomeSection row, then the About page.
    why_style = SectionStyle.objects.filter(section="why").first()
    home_why = HomeSection.objects.filter(section_type="home_why").first()
    about = AboutSection.objects.first()
    if why_style:
        _copy_mapped(why_style, "title", home_why, "title")
        _copy_mapped(why_style, "subtitle", home_why, "content")
        _copy_mapped(why_style, "title", about, "why_choose_us_title")
        _copy_mapped(why_style, "subtitle", about, "why_choose_us_content")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_herosection_page'),
    ]

    operations = [
        # Preserve the on-screen text before the duplicate columns disappear.
        migrations.RunPython(move_text_into_section_styles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='subheading_ar',
        ),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='subheading_en',
        ),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='subheading_fa',
        ),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventcountdown',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='content_fa',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='subheading_ar',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='subheading_en',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='subheading_fa',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='title_fa',
        ),
        migrations.AlterField(
            model_name='homesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown beside the text of this block', null=True, upload_to='home/', verbose_name='Image'),
        ),
    ]
