# Generated by Django 4.2.30 on 2026-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_eventcountdown_subheading_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Optional — makes the whole card a link, for example /page/portfolio/ or https://example.com', max_length=500, verbose_name='Link URL'),
        ),
    ]
